// SPDX-License-Identifier: GPL-3.0-or-later
// AUTO-GENERATED by scripts/build-emoji-sprite.mjs - do not edit by hand.
//
// Geometry for public/emoji-sprite/emoji-sprite.webp.
// Art: Noto Emoji (https://github.com/googlefonts/noto-emoji), SIL OFL 1.1.
// Regenerate with: pnpm run gen:emoji-sprite
//
// Deliberately NO emoji -> index table. This script lays the sheet out in palette order,
// reading the same __data__/emoji-categories.json the runtime reads, so an emoji's cell
// index IS its position in REACTIONS. Emitting the map would put a second copy of every
// palette emoji string into every content-script bundle, against the ceiling
// scripts/check-bundle-budget.mjs holds. ui/emoji-sprite.ts derives the index instead; the
// signature below is what makes that derivation safe to trust.

export const SPRITE_COLS = 25;
export const SPRITE_ROWS = 26;
export const SPRITE_CELL = 72;
export const SPRITE_FILE = "emoji-sprite/emoji-sprite.webp";

// The palette this sheet was rasterized from: how many cells it holds, and an
// order-sensitive checksum of the emoji in cell order. emoji-sprite-coverage.test.ts
// recomputes both from the live palette, so a sheet built against a different - or merely
// reordered - palette fails the suite instead of silently rendering the wrong glyph for
// every emoji after the first change.
export const SPRITE_PALETTE_SIZE = 634;
export const SPRITE_PALETTE_SIGNATURE = "fa4e5d5e";
